// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnkadwvhmvwvakmpgitn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNua2Fkd3ZobXZ3dmFrbXBnaXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODc2MjIsImV4cCI6MjA2ODg2MzYyMn0.CshllfoSQlBfKWCuDKpPO6xsqYXLd4qJdrGpY3nHmMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});